name: Deploy Project

on:
  push:
    branches:
      - develop  # Ветка, на которую будет триггериться деплой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install --legacy-peer-deps

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and restart services on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            # Deploy the application using rsync
            rsync -avz --delete /local/path/to/deployment ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/MBmanagemenet/
          
            # Restart services on the server
            sudo systemctl restart nginx
            pm2 restart back  # Замените 'back' на имя вашего pm2 процесса
          EOF
